class Locators():
    base_url = "https://www.amazon.com.tr/"
    search_box_locator_id = "twotabsearchtextbox"
    search_box_text = "samsung galaxy m12"
    search_summit_button_id = "nav-search-submit-button"
    close_cookie_name = "accept"
    product_title = "productTitle"
    product = "span[class='a-size-base-plus a-color-base a-text-normal']"
    product_color = "//*[@id='a-autoid-13-announce']/div/div[1]/img"
    get_color = "//*[@id='variation_color_name']/div/span"
    product_size = "//*[@id='productOverview_feature_div']/div/table/tbody/tr[5]/td[2]/span"
    availability = "//*[@id='availability']/span"
    f_price = "span[class = 'a-price-decimal']"
    sym_price = "span[class = 'a-price-symbol']"
    price = "span[class = 'a-price-whole']"
    add_chart_button = "//*[@id='add-to-cart-button']"
    product_amount = "//*[@id='sw-subtotal-item-count']"
